### ISSUE TITLE
use_ssl=False ?

### ISSUE THREAD

**Issue by rsignell** [mpiannucci/gribberish#55]
@mpiannucci , this isn't really a gribberish issue, but I saw you are specifying `use_ssl=False` when reading data with fsspec:
```
import ujson
from gribberish.kerchunk import scan_gribberish

so = {"anon": True, "use_ssl": False}
json_dir = 'hrrr_subhourly/'
```
 and was wondering:
Did you get a noticible performance improvement?
If so, do you think that should be a best practice when reading any scientific data?

**Comment by mpiannucci** [comment]
Nope I should get rid of that... it is a relic from a time when my VPN killed SSL functionality. 

Thanks for the reminder to clean that up!
