### ISSUE TITLE
Question: GRIB 1 support?

### ISSUE THREAD

**Issue by kingkong-cmd** [mpiannucci/gribberish#58]
Trying to read GRIB v1 files from [Norwegian weather service](https://hjelp.yr.no/hc/no/articles/360009342993-V%C3%A6rdata-i-GRIB-format) with xarray/gribberish, but getting errors, which I am unable to decipher. I am able to read the files using xarray/cfgrib, but getting some warnings. 

Does this mean xarray/gribberish cannot read GRIB v1 files or something wrong with the files?

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/xarray/backends/api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
  File "/venv/lib/python3.10/site-packages/gribberish/gribberish_backend.py", line 38, in open_dataset
    dataset =  parse_grib_dataset(
ValueError: No valid GRIB messages found
```

**Comment by mpiannucci** [comment]
Yeah this can only read grib2 unfortunately. I would love to support grib 1 but I personally dont have much use for it so hard to dedicate the time needed

**Comment by kingkong-cmd** [comment]
> Yeah this can only read grib2 unfortunately. I would love to support grib 1 but I personally dont have much use for it so hard to dedicate the time needed

Understood, many thanks. I understand it's a bit of a dated format anyway.
