### ISSUE TITLE
Make `mod parameters` public?

### ISSUE THREAD

**Issue by JackKelly** [mpiannucci/gribberish#59]
`mod parameters` is currently declared private in [`templates/product/mod.rs`](https://github.com/mpiannucci/gribberish/blob/c3c22f4d2a0405e85ed3a8dc3c0c349a89438657/gribberish/src/templates/product/mod.rs#L7).

Would you consider making `parameters` public, please?

(All the other modules in `templates/product/mod.rs` are public. And all the modules in `templates/product/parameters/mod.rs` are public, too)

## Why?!
I should explain my use-case, just in case I'm barking up the wrong tree!

[`hypergrib`](https://github.com/JackKelly/hypergrib) is all about lazily loading GRIB files from cloud object storage for huge multi-GRIB datasets.

Given a key (consisting of the NWP variable name, reference time, forecast step, vertical level, and ensemble member)  `hypergrib` needs to lookup the location of the relevant GRIB message (i.e. the path of the GRIB file, the byte offset, and message length).

The plan is for `hypergrib` to maintain a `HashMap<Key, MessageLocation>`.

The `Key` _could_ be a `String` generated by [`Message:key`](https://github.com/mpiannucci/gribberish/blob/e1c80d37b36e4298456a11fc3918cfb3545373eb/gribberish/src/message.rs#L101-L148) (which, if I've understood correctly, outputs strings like `"TEMP20170101095050:phyfcst"`) (I'd need to append the ensemble member).

But I'd prefer `Key` to be a `struct` like this:

```rust
struct Key {
  reference_time: DateTime<Utc>,
  forecast_step: TimeDelta,
  product: Product,
  vertical_level: VerticalLevel,
  ensemble_member: EnsembleMember,
}
```

where `Product` would be an `enum` like this:

```rust
use gribberish::templates::product::parameters::meteorological;

enum Product {
  TemperatureProduct(meteorological::TemperatureProduct),
  MoistureProduct(meteorological::MoistureProduct),
  MomentumProduct(meteorological::MomentumProduct),
  CloudProduct(meteorological::CloudProduct),
  // etc.
}
```

But this won't compile because `parameters` is private!

(Please let me know if you think this is a bad way to structure things!)

**Comment by mpiannucci** [comment]
making them public is fine with me!

**Comment by JackKelly** [comment]
Closing this issue now that the PR is merged
